config/routes.rb
Rails.application.routes.draw do
  root "tweeets#index"
  resources :tweeets do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
  validates_length_of :tweeet, :within =>1...141
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/channels/application_cable/channel.rb
module ApplicationCable
  class Channel < ActionCable::Channel::Base
  end
end

app/controllers/channels/application_cable/connection.rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base
  end
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: [:show, :edit, :update, :destroy,]

  def index
    @tweeets = Tweeet.all.order("created_at DESC")
  end

  def show
  end

  def new
    if params[:back]
      @tweeet = Tweeet.new(tweeet_params)
    else
      @tweeet = Tweeet.new
    end
  end

  def edit
  end

  def create
    @tweeet = Tweeet.new(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to root_path, notice: 'Tweeet was successfully created.' }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
      @tweeet = Tweeet.new(tweeet_params)
      render :new if @tweeet.invalid?
    end
    def back
      @tweeet = Tweeet.edit(tweeet_params)
      render :choose_new_or_edit if @tweeet.invalid?
    end
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to root_path, notice: 'Tweeet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tweeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: 'Tweeet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_tweeet
    @tweeet = Tweeet.find(params[:id])
  end

  def tweeet_params
    params.require(:tweeet).permit(:tweeet)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
  def choose_new_or_edit
         if action_name == 'new'
             confirm_tweeets_path
         elsif action_name == 'edit'
             tweeet_path
         end
     end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twittter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-info">
      <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-5">Twittter</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
      </div>
    </div>
      <div id="navbarExample" classs="navbar-menu"
        <div class="navbar-end">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'New Tweeet', new_tweeet_path, class: "button is-info is-inverted" %>
            </p>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
<footer class="footer">
<div class="content has-text-centered">
  <p>
    <strong>Twitter Clone</strong> by <a href="https://jgthms.com">Ts'olo David</a>. Hello World
     <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Ts'olo David</a>.
  </p>
</div>
</footer>
</html>

app/views/tweeets/_feed.html.erb
<div class="column is-half">
  <article class="media box">
    <figure class="media-left">
      <p class="image" is-64x64>
        <img src="https://bulma.io/images/placeholders/64x64.png">

      </p>
    </figure>
    <div class="media-content">
      <%= render"tweeets/form" %>
    </div>
  </article>
</div>
<% @tweeets.each do | tweeet | %>
  <div class="box">
    <<article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <img src="https://bulma.io/images/placeholders/64x64.png">
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <strong> Tsolo David</strong><br/>
          <small>@mahase</small><br/>
          <p><%= tweeet.tweeet %></p>
        </div>
        <nav class="level">
          <div class="level-left is-mobile">
            <%= link_to tweeet, class: "level-item" do %>
              <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to edit_tweeet_path(tweeet), class: "level-item" do %>
              <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
            <% end %>
            <%= link_to tweeet, method: :delete, data: { confirm: "Are you suree you want to delete this tweet?"
              } do %>
                <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
              <% end %>
          </div>
        </nav>
      </div>
    </article>
  </div>
<% end %>

app/views/tweeets/_form.html.erb
<%= form_with(model: @tweeet, local: true, url: choose_new_or_edit) do |form| %>
  <% if @tweeet.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(tweeet.errors.count, "error") %> prevented this tweet from being saved :</h2>

  <ul>
    <% tweeet.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
  </div>
  <% end %>

  <div class="field">

    <%= form.text_area :tweeet %>
  </div>

  <div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/tweeets/confirm.html.erb
<h3> Confirmation </h3>
<%= form_with(model: @tweeet, local:true) do |form| %>
    <%= form.hidden_field :tweeet %>
    <p>Your Tweet: <%= @tweeet.tweeet %></p>
  <%= form.submit  "Submit" %>
<% end %>

<%= form_with(model: @tweeet, url: new_tweeet_path, local:true,method: 'get') do |form| %>
    <%= form.hidden_field :tweeet %>
  <%= form.submit  "back", name: 'back' %>
<% end %>

app/views/tweeets/edit.html.erb
<h1>Editing Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Show', @tweeet %> |
<%= link_to 'Back', tweeets_path %>

app/views/tweeets/index.html.erb
<h1>Tweets</h1>
    <% @tweeets.each do |tweeet| %>
      <hr>
        <div>
          <%= tweeet.tweeet %>
        </div>
        <div>
          <%= link_to 'Post', tweeet %>
          <%= link_to 'Edit', edit_tweeet_path(tweeet) %>
          <%= link_to 'Destroy', tweeet, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    <% end %>
<br>

app/views/tweeets/new.html.erb
<h1>New Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Back', tweeets_path %>

app/views/tweeets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweeet:</strong>
  <%= @tweeet.tweeet %>
</p>

<%= link_to 'Edit', edit_tweeet_path(@tweeet) %> |
<%= link_to 'Back', tweeets_path %>